version: '3.8'

services:
  bookstore-api:
    image: bookstore-image
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
